### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by won13y** [wilselby/ROS_quadrotor_simulator#1]
I have compile problem as following

Would you please let me know how to fix it?
(I cannot find planning_msgs ROS package from website)

```
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "planning_msgs"
  with any of the following names:

    planning_msgsConfig.cmake
    planning_msgs-config.cmake

  Add the installation prefix of "planning_msgs" to CMAKE_PREFIX_PATH or set
  "planning_msgs_DIR" to a directory containing one of the above files.  If
  "planning_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  ROS_quadrotor_simulator/quad_control/CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/wkyoun/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/wkyoun/catkin_ws/build/CMakeFiles/CMakeError.log".
```

**Comment by wilselby** [comment]
This error results from not having PX4's mav_comm package. This can be solved with the following code:

cd $WORKSPACE/src
git clone https://github.com/PX4/mav_comm.git

[This tutorial ](https://github.com/AurelienRoy/ardupilot_sitl_ros_tutorial/blob/master/Tutorial%20to%20setup%20SITL%20Gazebo%20on%20Windows%20-%20v0.8.pdf)provides scripts (labeled steps 3-5) for installing ROS, Gazebo, ArduCopter, and other supporting software packages. The “Step 3″ script installs the latest Github version of Ardupilot and JSBSim simulator. The “Step 4″ script installs ROS Indigo (the full desktop version) and several dependencies including DRCsim and MAVROS required for the ArduPilot simulation.

Let me know if that helps. Thanks for pointing it out!

**Comment by won13y** [comment]
Thank you for the reply
I have encounter another problem as following

    CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:296 (message):
      catkin_package() include dir 'include/eigen3' does not exist relative to
      '/home/wkyoun/catkin_ws/src/moveit_core'
    Call Stack (most recent call first):
      /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:98 (_catkin_package)
      moveit_core/CMakeLists.txt:64 (catkin_package)

It seems to me that moveit_core package require eigen3 to be installed.

**Comment by won13y** [comment]
@wilselby 

I have eigen3 packages as followings

wkyoun@wkyoun-15Z960-GA70K:~$ dpkg -p libeigen3-dev 
    Package: libeigen3-dev
    Priority: extra
    Section: libdevel
    Installed-Size: 3729
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Architecture: all
    Source: eigen3
    Version: 3.2.0-8
    Provides: libeigen2-dev
    Depends: pkg-config
    Suggests: libeigen3-doc, libmrpt-dev
    Size: 494158
    Description: lightweight C++ template library for linear algebra
     Eigen 3 is a lightweight C++ template library for vector and matrix math,
     a.k.a. linear algebra.
 .
     Unlike most other linear algebra libraries, Eigen 3 focuses on the simple
     mathematical needs of applications: games and other OpenGL apps, spreadsheets
     and other office apps, etc. Eigen 3 is dedicated to providing optimal speed
     with GCC. A lot of improvements since 2-nd version of Eigen.
    Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
    Homepage: http://eigen.tuxfamily.org

**Comment by won13y** [comment]
@wilselby 
I delete  ${EIGEN3_INCLUDE_DIRS} in moveit_core/CMakeLists.txt:64 as followings:

catkin_package(
  INCLUDE_DIRS
    ${THIS_PACKAGE_INCLUDE_DIRS}
    ${OCTOMAP_INCLUDE_DIRS}

catkin make works correctly at some points, but it produce error as followings

it seems to me that there are errors of source code in ROS_quadrotor_simulator/quad_control/src/library/quad_controller.cpp.

Would you please let me know how to fix it?

    In file included from /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library/quad_controller.cpp:23:0:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/include/quad_control    /quad_controller.h:69:43: error: ‘mav_msgs::CommandTrajectory’ has not been declared
       void CalculatePositionControl(mav_msgs::CommandTrajectory wp, nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output);
                                           ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:138:61: error: variable or field ‘CalculatePositionControl’ declared void
     void PositionController::CalculatePositionControl(mav_msgs::CommandTrajectory wp,     nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output){
                                                             ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:138:51: error: ‘CommandTrajectory’ is not a member of ‘mav_msgs’
     void PositionController::CalculatePositionControl(mav_msgs::CommandTrajectory wp,     nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output){
                                                   ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:138:102: error: expected primary-expression before ‘current_gps’
     void PositionController::CalculatePositionControl(mav_msgs::CommandTrajectory wp,     nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output){
                                                                                                      ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:138:155: error: expected primary-expression before ‘*’ token
     void PositionController::CalculatePositionControl(mav_msgs::CommandTrajectory wp,     nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output){
                                                                                                                                                           ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:138:156: error: ‘des_attitude_output’ was not declared in this scope
     void PositionController::CalculatePositionControl(mav_msgs::CommandTrajectory wp,     nav_msgs::Odometry current_gps, mav_msgs::CommandRollPitchYawrateThrust *des_attitude_output){
                                                                                                                                                            ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/library    /quad_controller.cpp:490:1: error: expected ‘}’ at end of input}^
    make[2]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/quad_controller.dir/src/library    /quad_controller.cpp.o] Error 1
    make[1]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/quad_controller.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Linking CXX shared library /home/wkyoun/catkin_ws/devel/lib/librealsense_camera_nodelet.so
    [ 64%] Built target realsense_camera_nodelet
    [ 64%] Building CXX object octomap_mapping/octomap_server/CMakeFiles/octomap_server.dir    /src/TrackingOctomapServer.cpp.o
    Linking CXX shared library /home/wkyoun/catkin_ws/devel/lib/liboctomap_server.so
    [ 64%] Built target octomap_server
    make: *** [all] Error 2
    Invoking "make -j4 -l4" failed

**Comment by wilselby** [comment]
It looks like you downloaded the moveit_core package from source into your catkin/src folder. I installed my moveit from the Debian packages and not from source. I don't have moveit_core/CMakeLists.txt in my moveit_core directory but my package.xml file has a dependency on eigen not eigen3.

Remove it and try installing the moveit package from the Debian packages. 

sudo apt-get install ros-indigo-moveit-full

This should also install the moveit_core package and all dependencies. You could run this to double check it was installed:

sudo apt-get install ros-indigo-moveit-core

 For future reference, all ROS packages from debian packages and not from source. I linked to the ROS wiki for all these pages as a reference.

If not you can run:

apt-cache show ros-indigo-moveit-core

My version was 0.7.1 if you want to compare.

I ran dpkg -p libeigen3-dev and got the same results as you did for the eigen3 package.

As for this: "Main error is due to the absence of mav_msgs::CommandTrajectory in the source code"

This message is included in the mav_comm code you installed previously (https://github.com/PX4/mav_comm/tree/master/mav_msgs/msg) I would double check it is in your catkin/src folder and see if perhaps there were errors associated with moveit dependencies that caused this to fail.

-Wil

**Comment by won13y** [comment]
@wilselby 

Thank you for the reply

I guess this is the last complie problem that I am facing

It seems to me that the problem is related to "mav_msgs/include/eigen_mav_msgs.h"

Actually I can find the file(eigen_mav_msgs.h in mav_msgs),

I don't know why this problem happens.

Would you please let me know how to fix it?

    [ 85%] [ 85%] Building CXX object rocon/src/rocon_tutorials/concert_tutorials/turtle_concert/CMakeFiles/turtle_stroll.dir/src/turtle_stroll.cpp.o

    [ 85%] Building CXX object turtlebot_apps/turtlebot_follower/CMakeFiles/turtlebot_follower.dir/src/follower.cpp.o

    Building CXX object turtlebot_apps/turtlebot_panorama/CMakeFiles/panorama.dir/src/panorama.cpp.o

    In file included from /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes/waypoint_publisher_node.cpp:21:0:

    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes
    /waypoint_publisher_node.h:33:45: fatal error: mav_msgs/include/eigen_mav_msgs.h: No such file or directory
 
    #include <mav_msgs/include/eigen_mav_msgs.h>
                                             ^
compilation terminated.

**Comment by wilselby** [comment]
Looking at the waypoint_publisher_node.h [here](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_control/src/nodes/waypoint_publisher_node.h) the include should be:

`#include <mav_msgs/eigen_mav_msgs.h>`

As you pointed out, that file path isn't mav_msgs/include/eigen_mav_msgs.h

It looks like somehow the version you are using is looking for an /include/ folder that isn't there.

I would try just using the following code and re-compiling. I would also look for other includes in the header that might also have that extra "/include/" and remove it.

Try just this:

`#include <mav_msgs/eigen_mav_msgs.h>`

-Wil

**Comment by won13y** [comment]
@wilselby 

Thank you for the comment
The previous problem was solved, but I met another problem as followings

    In file included from /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes/waypoint_publisher_node.cpp:21:0:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.h:92:13: error: ‘EigenCommandTrajectory’ in namespace ‘mav_msgs’ does not name a type
       mav_msgs::EigenCommandTrajectory command_trajectory;
                 ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.h:93:13: error: ‘EigenCommandTrajectory’ in namespace ‘mav_msgs’ does     not name a type
       mav_msgs::EigenCommandTrajectory threedNav_trajectory;
             ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::CommandTrajectoryCallback(const     CommandTrajectoryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:102:3: error: ‘eigenCommandTrajectoryFromMsg’ is not a member of     ‘mav_msgs’
       mav_msgs::eigenCommandTrajectoryFromMsg(*command_trajectory_msg, &command_trajectory);
       ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:102:69: error: ‘command_trajectory’ was not declared in this scope
       mav_msgs::eigenCommandTrajectoryFromMsg(*command_trajectory_msg, &command_trajectory);
                                                                     ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::threedNavCallback(const CommandTrajectoryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:111:3: error: ‘eigenCommandTrajectoryFromMsg’ is not a member of     ‘mav_msgs’
       mav_msgs::eigenCommandTrajectoryFromMsg(*threed_nav_msg, &threedNav_trajectory);
           ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:111:61: error: ‘threedNav_trajectory’ was not declared in this scope
       mav_msgs::eigenCommandTrajectoryFromMsg(*threed_nav_msg, &threedNav_trajectory);
                                                             ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::OdometryCallback(const OdometryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:127:63: error: ‘command_trajectory’ was not declared in this scope
       desired_wp.position.x = current_gps_.pose.pose.position.x + command_trajectory.position(0);
                                                               ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:239:44: error: ‘threedNav_trajectory’ was not declared in this scope
     waypointBF = control_mode.rotateGFtoBF(threedNav_trajectory.position(0)-current_gps_.pose.pose.position.x, threedNav_trajectory.position(1)-current_gps_.pose.pose.position.y, threedNav_trajectory.position(2), 0, 0, gps_yaw);
                                            ^
    [ 90%] Building CXX object navigation/robot_pose_ekf/CMakeFiles/robot_pose_ekf.dir/src/odom_estimation_node.cpp.o
    make[2]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/waypoint_publisher_node.dir/src/nodes/waypoint_publisher_node.cpp.o] Error 1
    make[1]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/waypoint_publisher_node.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....


It seems to me that following structures(
EigenCommandTrajectory
eigenCommandTrajectoryFromMsg
command_trajectory
threedNav_trajectory
threedNav_trajectory) was not declared in this scope
**(ROS_quadrotor_simulator/quad_control/src/nodes/waypoint_publisher_node.cpp)**

Would you please help me out?

**Comment by wilselby** [comment]
Can you make sure that your [CMakeLists.txt](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_control/CMakeLists.txt) and [package.xml](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_control/package.xml) in the quad_control package match the ones I linked? Specifically, make sure that "mav_msgs" is included in both of them. It is in a few places in each file.

These structures are defined in the following files so not sure where the disconnect is. Maybe you can use the absolute path instead of the relative path?
[mav_msgs/eigen_mav_msgs.h](https://github.com/PX4/mav_comm/blob/5e0a51c242f9f8ac05c645a728ea25621b69c860/mav_msgs/include/mav_msgs/eigen_mav_msgs.h)
[mav_msgs/conversions.h](https://github.com/PX4/mav_comm/blob/5e0a51c242f9f8ac05c645a728ea25621b69c860/mav_msgs/include/mav_msgs/conversions.h)

The variables command_trajectory and threedNav_trajectory are defined in [waypoint_publisher_node.h](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_control/src/nodes/waypoint_publisher_node.h) so make sure that file hasn't been accidentally modified. The definitions of those variables in that file is below.

mav_msgs::EigenCommandTrajectory command_trajectory;
mav_msgs::EigenCommandTrajectory threedNav_trajectory;

**Comment by won13y** [comment]
@wilselby 

Thank you for the comment
However, following problem still occurs,

Most of my problem are related to mav_msgs, but
I installed previously (https://github.com/PX4/mav_comm/tree/master/mav_msgs/msg),
and I double check it is in your catkin/src folder 


    In file included from /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:21:0:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.h:92:13: error: ‘EigenCommandTrajectory’ in namespace ‘mav_msgs’ does     not name a type
       mav_msgs::EigenCommandTrajectory command_trajectory;
                 ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.h:93:13: error: ‘EigenCommandTrajectory’ in namespace ‘mav_msgs’ does     not name a type
       mav_msgs::EigenCommandTrajectory threedNav_trajectory;
                 ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::CommandTrajectoryCallback(const     CommandTrajectoryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:102:3: error: ‘eigenCommandTrajectoryFromMsg’ is not a member of     ‘mav_msgs’
       mav_msgs::eigenCommandTrajectoryFromMsg(*command_trajectory_msg, &command_trajectory);
       ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:102:69: error: ‘command_trajectory’ was not declared in this scope
       mav_msgs::eigenCommandTrajectoryFromMsg(*command_trajectory_msg, &command_trajectory);
                                                                     ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::threedNavCallback(const CommandTrajectoryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:111:3: error: ‘eigenCommandTrajectoryFromMsg’ is not a member of     ‘mav_msgs’
       mav_msgs::eigenCommandTrajectoryFromMsg(*threed_nav_msg, &threedNav_trajectory);
       ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:111:61: error: ‘threedNav_trajectory’ was not declared in this scope
       mav_msgs::eigenCommandTrajectoryFromMsg(*threed_nav_msg, &threedNav_trajectory);
                                                             ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp: In member function ‘void     quad_control::WaypointPublisherNode::OdometryCallback(const OdometryConstPtr&)’:
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:127:63: error: ‘command_trajectory’ was not declared in this scope
       desired_wp.position.x = current_gps_.pose.pose.position.x + command_trajectory.position(0);
                                                               ^
    /home/wkyoun/catkin_ws/src/ROS_quadrotor_simulator/quad_control/src/nodes    /waypoint_publisher_node.cpp:239:44: error: ‘threedNav_trajectory’ was not declared in this scope
         waypointBF = control_mode.rotateGFtoBF(threedNav_trajectory.position(0)-    current_gps_.pose.pose.position.x, threedNav_trajectory.position(1)-current_gps_.pose.pose.position.y,     threedNav_trajectory.position(2), 0, 0, gps_yaw);
                                            ^
    Linking CXX executable /home/wkyoun/catkin_ws/devel/lib/quad_control/position_controller_node
    [100%] Built target position_controller_node
    make[2]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/waypoint_publisher_node.dir    /src/nodes/waypoint_publisher_node.cpp.o] Error 1
    make[1]: *** [ROS_quadrotor_simulator/quad_control/CMakeFiles/waypoint_publisher_node.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Linking CXX executable /home/wkyoun/catkin_ws/devel/lib/quad_control/attitude_controller_node
    [100%] Built target attitude_controller_node
    make: *** [all] Error 2
    Invoking "make -j4 -l4" failed

**Comment by wilselby** [comment]
Can you confirm this part? I can't think of anything else right now:

"Can you make sure that your CMakeLists.txt and package.xml in the quad_control package match the ones I linked? Specifically, make sure that "mav_msgs" is included in both of them. It is in a few places in each file."

Alternatively, you can try to create your own test file and add the include statements one by one to see which one is causing the error.

**Comment by nishathussain** [comment]
Use rotor_simulator from link: https://github.com/wilselby/rotors_simulator

**Comment by wilselby** [comment]
I also updated the readme with some details about the required dependencies and installation instructions. Let me know if that helps.
