### ISSUE TITLE
Joystick trouble

### ISSUE THREAD

**Issue by aaravrav142** [wilselby/ROS_quadrotor_simulator#11]
Hi, 
I have successfully installed the package and everything seems to work fine. However, I am unable to get any response from the xbox 360 joystick to take off and land the quadroter. I have correctly configured the joystick and added the param /dev/input/js0 (for my case). When running the rosrun joy_node joy the joystick responds to the buttons, but not in the simulator. I am not sure how to fix this. I cant seem to find where the buttons are configured for the quadroter. Is it activated using a deadman switch? Please help. Thanks

**Comment by wilselby** [comment]
The joy.cpp file (https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_joystick_interface/src/joy.cpp) is where you can see which commands are tied to which controller buttons/joysticks.

Check the output of the command/roll_pitch_yawrate_thrust and command/trajectory topics and see if the commands are being published properly.

**Comment by aaravrav142** [comment]
Hi, 
I reinstalled everything and still the problem persists. 
When running.. 
```
$ rostopic echo /quad/command/roll_pitch_yawrate_thrust 
WARNING: no messages received and simulated time is active.
Is /clock being published?
```
I do not understand how to solve this problem. 
Thanks

**Comment by wilselby** [comment]
Hello,
Can you verify that the simulation isn't paused? Also, check the topic quad/joy and see if anything is published. 

Lastly, try the basic joy package [tutorial](http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick) to make sure your controller is properly configured and working.

**Comment by aaravrav142** [comment]
Hi,

Thanks a lot. My bad. I should I have checked whether the simulation was running or not. It was on pause by default and I was struggling. Everything working fine now. One question. When using the joystick the movements of the quadcopter are very strong. How to smooth out the motions using the controller. Its very difficult to control using the controller. Also how did you made the waypoints txt when flying the vehicle. Did you register autonomously all the points. Please teach me. Thanks

**Comment by wilselby** [comment]
No worries! Glad you got it working.

You can modify the PID values in the .yaml files to change the response to the joystick values. [Here's one ](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_control/resource/attitude_controller.yaml)for example for the attitude controllers.

You could also change the max joystick outputs in [this file](https://github.com/wilselby/ROS_quadrotor_simulator/blob/master/quad_joystick_interface/src/joy.cpp).

As for the waypoints .txt files, I made those manually. I opened up Gazebo on pause with the quadrotor in the desired world file. I then used the Gazebo GUI to move the quadrotor around and recorded the positions displayed by Gazebo. I then put those values into a .txt file. You may have to play around with the timing some once you get the initial .txt file working.
