### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'kit_c.xacro'

### ISSUE THREAD

**Issue by shuklam20** [wilselby/ROS_quadrotor_simulator#12]
Hi,
I am trying to follow all the steps that you have mentioned, however when I enter (during the model Verification part)
`rosrun xacro xacro.py kit_c.xacro -o /tmp/kit_c.urdf`
I get an error:
> Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 673, in main
    f = open(args[0])
IOError: [Errno 2] No such file or directory: 'kit_c.xacro'

and the next command:
`check_urdf kit_c.urdf`
gives:
> Error:   Error document empty.
         at line 72 in /build/buildd/urdfdom-0.2.10+dfsg/urdf_parser/src/model.cpp
ERROR: Model Parsing the xml failed

Can you please help me with? Do I need to install something extra? I am using Ubuntu 14.04 Trusty version and a newbie to ROS.

**Comment by medhijk** [comment]
I am facing the same problem too. I think the error shows because there are issues with the installation instructions itself. As per the instructions, `$ git clone https://github.com/wilselby/rotors_simulator` installs `rotors_simulator` which does not contain the file `kit_c.xacro`. The missing file is available only in this current package, `ROS_quadrotor_simulator`, and there is no instruction to install this package before parsing the urdf.

**Comment by wilselby** [comment]
Thanks for the head's up and I apologize for the confusion. I've updated the readme to make the process more clear. Thanks again!

**Comment by kylemanna** [comment]
Are you sure?

**Comment by hassankhalil766** [comment]
rosrun xacro xacro.py kit_c.xacro -o /tmp/kit_c.urdf
xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order

**Comment by wilselby** [comment]
Those look like warnings, not an error?

**Comment by hassankhalil766** [comment]
xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
No such file or directory: kit_c.xacro None None

**Comment by hassankhalil766** [comment]
xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
No such file or directory: kit_c.xacro None None

**Comment by hassankhalil766** [comment]
Anyone help me with this ?

**Comment by hassankhalil766** [comment]
rosrun xacro xacro.py kit_c.xacro -o /tmp/kit_c.urdf
xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
No such file or directory: kit_c.xacro None None

that's the error
