### ISSUE TITLE
Not able to finish the catkin_make

### ISSUE THREAD

**Issue by akshaya95** [wilselby/ROS_quadrotor_simulator#14]
I am not able to figure out what is wrong with the process I followed as I am doing exactly the same as mentioned in your post. I am stuck at 64% make. Below is the error I am getting.

make[2]: *** [ROS_quadrotor_simulator/action_controller/CMakeFiles/action_controller.dir/src/actionController.cpp.o] Error 1
make[1]: *** [ROS_quadrotor_simulator/action_controller/CMakeFiles/action_controller.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [ROS_quadrotor_simulator/moveit_simple_controller_manager/CMakeFiles/moveit_simple_controller_manager.dir/src/moveit_simple_controller_manager.cpp.o] Error 1
make[1]: *** [ROS_quadrotor_simulator/moveit_simple_controller_manager/CMakeFiles/moveit_simple_controller_manager.dir/all] Error 2
Linking CXX executable /home/akshaya/bhag_ws/devel/lib/rotors_joy_interface/rotors_joy_interface
[ 64%] Built target rotors_joy_interface
Linking CXX shared library /home/akshaya/bhag_ws/devel/lib/libroll_pitch_yawrate_thrust_controller.so
[ 64%] Built target roll_pitch_yawrate_thrust_controller
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

Please let me know how to sort this out. Thank you/

**Comment by wilselby** [comment]
Sometimes I have to run catkin_make several times in a row for a successful compile. I can't really see anything specific in the output above.

**Comment by wilselby** [comment]
This seems odd:
fix-unused-typedef-warning.patch: No such file

You could also try just making the glog pakcage by itself.

**Comment by Andreluizfc** [comment]
I tried to use the old version of Glog 0.3.4 and it worked. What Glog really do?

**Comment by wilselby** [comment]
I believe glog is just legacy from some of the other packages I utilized. It's likely not completely necessary.
