### ISSUE TITLE
catkin_make: MultiDofFollowJointTrajectoryAction.h no such file 

### ISSUE THREAD

**Issue by NuenoB** [wilselby/ROS_quadrotor_simulator#15]
Hi.
I try to make a catkin_make in the part of [install-rotors-simulator](https://github.com/wilselby/ROS_quadrotor_simulator#install-rotors-simulator) and it fail 
I install apart from the tutorial, moveIt and move_core
I think this is the error
`/catkin_ws/src/ROS_quadrotor_simulator/action_controller/src/actionController.cpp:6:67: fatal error: action_controller/MultiDofFollowJointTrajectoryAction.h: No such file or directory  
#include <action_controller/MultiDofFollowJointTrajectoryAction.h>`
the moveIt version is 0.7.12-0trusty-20170915-165807-0800 i think 

thanks

**Comment by NuenoB** [comment]
hi i think i fix it,
i make some changes to package.xml and CMakeLists.txt
But i think the important thing is i make a separate `catkin_make --pkg action_controller` after it fail, and work

**Comment by jnguyen596** [comment]
Hi, could you show me what you did to get this to work?

Thank you

**Comment by jianhuaixie** [comment]
i following the step ,but still have the same problem.

**Comment by wilselby** [comment]
The MultiDofFollowJointTrajectoryAction.h file is autogenerated. Try compiling the action_controller package by itself to generate that file.

catkin_make --pkg action_controller
