### ISSUE TITLE
Yawing not working

### ISSUE THREAD

**Issue by nishathussain** [wilselby/ROS_quadrotor_simulator#2]
apart from ROS_quadrotor_simullator which other packages are required ? do we need rotors_simulator (which branch) too and SITL ROS gazebo.

I compiled with 'wilselby/rotors_simulator'. It works but unable to control yaw of the quad.

Can we use it with arducopter SITL??

**Comment by wilselby** [comment]
The exact dependencies will depend on which launch file you are trying to use. I will start with just the requirements for basic joystick control. For more details, please see my tutorial here:
https://www.wilselby.com/research/ros-integration/development-environment-setup/

I used this script to get my initial ROS install setup:
https://github.com/AurelienRoy/ardupilot_sitl_ros_tutorial/blob/master/scripts/step_4_install_ros.sh

Specifically, it installs the following  packages. See the script for more install details.
sudo apt-get -y install  [package] with the following packages:
ros-indigo-desktop-full
python-rosinstall
ros-indigo-octomap-msgs   
ros-indigo-joy
ros-indigo-geodesy
ros-indigo-octomap-ros     
unzip
drcsim
ros-indigo-mavros
ros-indigo-mavros-extras

The next script installs some more repositories (https://github.com/AurelienRoy/ardupilot_sitl_ros_tutorial/blob/master/scripts/step_5_create_ros_workspace.sh)
git clone https://alexbuyval@bitbucket.org/alexbuyval/arducopter_sitl_ros.git 
git clone https://github.com/PX4/mav_comm.git

I also installed the jstest-gtk package to use the Xbox controller input.

I also installed the master branch of the RotorS simulator:
https://github.com/ethz-asl/rotors_simulator

I never attempted to integrate the Arducopter SITL with this code base.

Hope this helps. Would be interested in knowing which launch file you used and if you are able to see yaw commands coming from your input device to the attitude control nodes.

**Comment by nishathussain** [comment]
Thanks Wil,
I am now able to do yaw.. As I was using Gazebo 6.6 ver [[solution](https://github.com/ethz-asl/rotors_simulator/commit/71c1ddef1ff42345090a2dd8e112683ecf7ac46f?_pjax=%23js-repo-pjax-container#diff-3cf18422550da5a0e7b8ad5bdb3ad8c6)].

**Comment by nishathussain** [comment]
Please share tutorials links for Octomap and moveit planning if you have any.
Thanks
Nishat

**Comment by wilselby** [comment]
Nishat,

This page covers 3D perception and path planning to include some Octomap and MoveIt guides

https://www.wilselby.com/research/ros-integration/3d-mapping-navigation/

-Wil
