### ISSUE TITLE
Grass Plane and VRC Heightmap 1 models

### ISSUE THREAD

**Issue by danieljeswin** [wilselby/ROS_quadrotor_simulator#20]
model://grass_plane and model://vrc_heightmap_1 models do not exist

**Comment by wilselby** [comment]
Those are not included in this package but should be included with ROS Gazebo. You can find them online and move them into your Gazebo model folder.

You could also just install this package:
https://github.com/ethz-asl/rotors_simulator/tree/master/rotors_gazebo/models
