### ISSUE TITLE
[ERROR] [1512140180.555562173, 0.340000000]: Client [/move_group] wants topic /multi_dof_joint_trajectory_action/feedback to have datatype/md5sum [action_controller/MultiDofFollowJointTrajectoryActionFeedback/bb90301ebf9ac17d9c3bcafa7a141cba], but our version has [action_controller/MultiDofFollowJointTrajectoryActionFeedback/0611ea4a62fe3c6e8470a86482016c70]. Dropping connection. [ERROR] [1512140180.655915619, 0.421000000]: Client [/action_controller] wants topic /multi_dof_joint_trajectory_action/goal to have datatype/md5sum [action_controller/MultiDofFollowJointTrajectoryActionGoal/762be92da0a19418188f1bfa9dab9fe5], but our version has [action_controller/MultiDofFollowJointTrajectoryActionGoal/1292bbe002476592a0f3166376533ba1]. Dropping connection.

### ISSUE THREAD

**Issue by benbenji** [wilselby/ROS_quadrotor_simulator#21]
hi ! 
When I run roslaunch roslaunch quad_3dnav quad_3dnav.launch I get the output:
[ERROR] [1512140180.555562173, 0.340000000]: Client [/move_group] wants topic /multi_dof_joint_trajectory_action/feedback to have datatype/md5sum [action_controller/MultiDofFollowJointTrajectoryActionFeedback/bb90301ebf9ac17d9c3bcafa7a141cba], but our version has [action_controller/MultiDofFollowJointTrajectoryActionFeedback/0611ea4a62fe3c6e8470a86482016c70]. Dropping connection. [ERROR] [1512140180.655915619, 0.421000000]: Client [/action_controller] wants topic /multi_dof_joint_trajectory_action/goal to have datatype/md5sum [action_controller/MultiDofFollowJointTrajectoryActionGoal/762be92da0a19418188f1bfa9dab9fe5], but our version has [action_controller/MultiDofFollowJointTrajectoryActionGoal/1292bbe002476592a0f3166376533ba1]. Dropping connection.
My environment is kinetic,Iknow there are some mistake of actioncontroller and moveit but I don't know the reason .could you please telll me?

**Comment by wilselby** [comment]
It looks like you need to make sure all of your ROS packages are up to date and then rerun catkin make.

**Comment by benbenji** [comment]
@wilselby 
Thank you very much man.It is word after I delete the ".h" file of message and rebuild again just as your word,but this is another question ,when I run " roslaunch quav_3D. quav_3D.launch" I could not found interface marker to  select the desired start and end states.

but It it ok when I run roslaunch quav_3d demo.launch,what is the problem?

**Comment by benbenji** [comment]
I solve this problem now,I have not set the fixed frame right  thank you very much again! @wilselby
