### ISSUE TITLE
Wilowgarage Map waypoint Nav

### ISSUE THREAD

**Issue by nishathussain** [wilselby/ROS_quadrotor_simulator#3]
In wilowgarage map. provided 48 waypoints are not executing properly. Robot is actually following points but outside the maze. some problem with coordinate system. How to generate waypoints file from gazebo environment ?

**Comment by wilselby** [comment]
Nishat,

Which waypoint file and Gazebo file are you using? They could be mixed up.

In general, to determine the waypoint locations, I loaded the Gazebo environment with the quadrotor model in it. With the simulation paused, I then manually dragged the quadrotor model around to each desired waypoint. I then read the X, Y, and Z location being reported by Gazebo on the the property/value menu. I can take a snapshot if this description is confusing.

Wil

**Comment by wilselby** [comment]
The waypoint files are stored in the quad_control/resource folder and are loaded in the waypoint_publisher_node. The kitchen world series of waypoint is loaded by default. Each line in the waypoint file is a waypoint and has the following entries [time (s), x, y, z, yaw (deg)]

The “waypoint mission” mode reads in a waypoint file that contains a series of waypoints and the time for them to be sent. First, the quadrotor must be in “GPS mode.” If enabled by pushing the “Y” button by default, the waypoint node will send each waypoint at the defined time.
