### ISSUE TITLE
Rivz Map orientation difference

### ISSUE THREAD

**Issue by nishathussain** [wilselby/ROS_quadrotor_simulator#4]
On launching below command:
roslaunch quad_2dnav quad_2dnav.launch

there is a 90[deg] yaw difference between robot pose compared to Map on rviz. [attached below image]
![rviz_image](https://cloud.githubusercontent.com/assets/1832512/20391912/8a7835c8-acfb-11e6-8ba2-40e7d67c84b5.jpg)

How to correct it?

Also could you please list the procedure involve to from assigning goal and following it.

**Comment by wilselby** [comment]
Nishat.

The easiest way to correct it is to use the "2D Pose Estimate" button before starting the simulation. Click the button and then drag the arrow in the direction of the quadrotor orientation. Check out the video below starting around 3:40.

https://youtu.be/orYNS6ntjnY

You can also set the initial orientation in one of the configuration files I believe.

The video above also documents how to set and follow goals. More detail is provided at the page below as well

https://www.wilselby.com/research/ros-integration/2d-mapping-navigation/

-Wil
