### ISSUE TITLE
Waypoint text, yaw does not get implemented

### ISSUE THREAD

**Issue by aaravrav142** [wilselby/ROS_quadrotor_simulator#41]
Hi Wilselby, 
When launching the simulator in any gazebo world with waypoint publisher node, I noticed that the three parameters, time, x, y, and z are executed smoothly. However the yaw value does not get executed (in degrees). More or less the quadcopter keeps the same orientation when it is started. I was wondering if there is a bug related to this issue. 

Thanks

**Comment by aaravrav142** [comment]
Found the issue and rectified it. Closing.

**Comment by wilselby** [comment]
What was the specific resolution?
