### ISSUE TITLE
Group 'Quad_base' is not a chain  

### ISSUE THREAD

**Issue by zychaoqun** [wilselby/ROS_quadrotor_simulator#6]
When I run 
`roslaunch quad_3dnav quad_3dnav.launch`
I get the error:
`[ERROR] [1480357098.245956879]: Group 'Quad_base' is not a chain `
`[ERROR] [1480357098.246008743]: Kinematics solver of type 'kdl_kinematics_plugin  
/KDLKinematicsPlugin' could not be initialized for group 'Quad_base'  `
`  [ERROR] [1480357098.246182732]: Kinematics solver could not be instantiated for  
joint group Quad_base.`

And I can't interact with the quadrotor in rviz, there is no interact marker on the model. What's wrong here? Is there anything I can do ? 
Thanks!

**Comment by nishathussain** [comment]
I also had same problem, then I ran MoveIt setup assistant to generate.
https://www.wilselby.com/research/ros-integration/3d-mapping-navigation/
it will generate files:
quad.srdf, ompl_planning.yaml, kinematics.yaml, joint_limits.yaml, fake_controllers.yaml
while doing so add a leaf to baselink to make it a chain.

**Comment by wilselby** [comment]
Additionally, you can set the "Kinematic Solver" to "None" in the "Planning Groups" section of the MoveIt! set-up assistant.

**Comment by wilselby** [comment]
Ajay,

Try running the MoveIt! Setup Assistant with the kinematic solver set to none since we are treating the quadrotor as a simple single object. I think the repo files were outdated and I left a kinematic solver in there to generate those.

The leaf comment with the baselink is something you can add in the MoveIt! setup assistant as well.

This page might help:
http://docs.ros.org/hydro/api/moveit_setup_assistant/html/doc/tutorial.html

**Comment by ajayfuloria** [comment]
Hi Wilselby !

thanks for reply. I did use Moveit! assistant to generate the files. The quad_3dnav.launch file does not get generated, so I replaced the files that you mention in your writeup in the repo folder and try and launch quad_3dnav.launch. Here is what I get

unused args [db] for include of [/home/merlin/catkin_ws/src/ROS_quadrotor_simulator/quad_3dnav/launch/move_group.launch]
The traceback for the exception was written to the log file

Files that I replace are 
+ quad.srdf 
+ ompl_planning.yaml 
+ kinematics.yaml 
+ joint_limits.yaml 
+ fake_controllers.yaml

**Comment by wilselby** [comment]
Ajay,

I updated the config files so you shouldn't need to regenerate them anymore. 

Try setting this argument to false in the quad_3dnav.launch file:
 <arg name="db" default="true" />
