### ISSUE TITLE
Octomap not generated in rviz

### ISSUE THREAD

**Issue by MaskedAfrican** [wilselby/ROS_quadrotor_simulator#7]
Hi,
I can't seem to generate an octomap in Rviz after running the quad_3dnav launch file This is my output in rviz. COuld you please kindly point me in the right direction.
![screenshot from 2017-02-02 13 03 02](https://cloud.githubusercontent.com/assets/8877826/22550521/5fb486be-e948-11e6-9668-170bce8e0e95.png)

Also, I get the following

```
[ERROR] [1486040499.742240912]: Group 'Quad_base' is not a chain
[ERROR] [1486040499.742304045]: Kinematics solver of type 'kdl_kinematics_plugin/KDLKinematicsPlugin' could not be initialized for group 'Quad_base'
[ERROR] [1486040499.742430888]: Kinematics solver could not be instantiated for joint group Quad_base.

```
However, I've set my Planning Groups to "None" and my "kinematics.yaml" file is empty.

**Comment by wilselby** [comment]
That image contains an initial Octomap. Are you saying you want to generate a map of the entire scenario? If so, you can manually pilot the quadrotor around the room or you can use the waypoint navigation to make the quadrotor follow a series of waypoints around the environment. 

The waypoints files are located here:
https://github.com/wilselby/ROS_quadrotor_simulator/tree/master/quad_control/resource

Verify it is loaded in your version of the [waypoint_publisher_node.cpp](https://github.com/wilselby/ROS_quadrotor_simulator/blob/e1adb9370fe2e585769c0735410594d8b27df301/quad_control/src/nodes/waypoint_publisher_node.cpp)

I used an Xbox controller and to enable the waypoint following I pressed "A" to go into GPS mode, "B" to launch the aircraft into a hover, and then "Y" to begin following the waypoints.

**Comment by MaskedAfrican** [comment]
Thanks, my controller was on initialised on /js4 so I just had to edit that in the launch file. I have a slightly related question and I was wondering if you could help me. Is there anyway to contact you by email?

**Comment by wilselby** [comment]
Yeah, email me here: accounts [at] wilselby [dot] com
