### ISSUE TITLE
Problem with Waypoint

### ISSUE THREAD

**Issue by paulb24** [wilselby/ROS_quadrotor_simulator#8]
Hi, I try to use your 3d naviguation simulation and mapping but I encoutered some problems : My waypoints seems to be broken when I start GPS Mode:

Start publishing #-800051560 waypoints 
Publishing #0 x=0.000000 y=0.000000 z=0.000000 yaw=0.000000, and wait for 0.000000s. 
Publishing #1 x=0.000000 y=0.000000 z=0.000000 yaw=0.000000, and wait for 0.000000s. 
Publishing #2 x=0.000000 y=0.000000 z=0.000000 yaw=0.000000, and wait for 0.000000s. 
Publishing #3 x=1.000000 y=0.000000 z=0.000000 yaw=0.000000, and wait for 0.000000s. 
Publishing #4 x=0.000000 y=5738431076726222389685073172365035292083665080233866238859201001629927867862798979344841711774851300900159035643711474254561155928353114223259579820953653833115358476566324156825600.000000 z=0.000000 yaw=0.000000, and wait for 0.000000s. 
Publishing #5 x=0.000000 y=0.000000 z=0.000000 yaw=0.000000, and wait for 34544653521011041425273226943955403952480793592875605810753909457570098983698963437919072949172041153383479371775238338564782493724937890751215317533162156809242810762819272704.000000s.

**Comment by wilselby** [comment]
Which waypoint file are you using? Can you confirm they are copies of the provided waypoint files or at least follow the similar format? The provided files are here for reference.
https://github.com/wilselby/ROS_quadrotor_simulator/tree/master/quad_control/resource

Also, check your copy of waypoint_publisher_node.cpp and make sure it is updated. 

Specifically, this line, where the waypoint file is specified:
`std::ifstream wp_file("/home/wil/ros/catkin_ws/src/arducopter_slam/quad_control/resource/kitchen_short_waypoints.txt"); `

**Comment by paulb24** [comment]
Yes, thank you very much !

**Comment by medhijk** [comment]
Can anyone tell me how this issue was/could be resolved? I checked that I loaded the correct my waypoint file and am having the same output as above on Indigo 14.04.

**Comment by wilselby** [comment]
So you checked that the waypoint_publisher_node.cpp points to the correct file and that file is formatted properly?

**Comment by medhijk** [comment]
Yes, I changed `std::ifstream wp_file("/home/wil/ros/catkin_ws/src/arducopter_slam/quad_control/resource/kitchen_short_waypoints.txt");` to my working folder `std::ifstream wp_file("/home/medhijk/catkin_ws/src/ROS_quadrotor_simulator/quad_control/resource/kitchen_short_waypoints.txt");`

Also do I need to have `arducopter_slam` directory for the code? Currently, I have the waypoint files located in subdirectories under `ROS_quadrotor_simulator` directory.

**Comment by wilselby** [comment]
I don't think you need that directory. I would create a simple waypoint file with a single point just to make sure the file is formatted properly.

**Comment by sohail70** [comment]
Hi @wilselby 
I'm experiencing the same problem and I did all of the above solutions which didn't work.
when I activate the mission mode with the joystick, the robot flies around insanely!
I have another issue. when I set a goal in quad_2dnav the robot doesn't follow the local planner path and just moves forward until it hits the wall.
P.S: quad_nav3d works ok.
